"""
Scalar API Reference view.

Serves the Scalar v1 docs UI pointing at the OpenAPI schema
generated by drf-spectacular.
"""

from django.http import HttpResponse
from django.views import View


SCALAR_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Haneus Cafe POS — API Docs</title>
  <style>
    body { margin: 0; padding: 0; }
  </style>
</head>
<body>
  <script
    id="api-reference"
    data-url="/api/schema/"
    data-configuration='{"theme": "default"}'
  ></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>
"""


class ScalarView(View):
    """Serve the Scalar API reference page."""

    def get(self, request, *args, **kwargs):
        return HttpResponse(SCALAR_HTML, content_type="text/html")
