-- SQL Schema for SariSari Store (SSMS)

CREATE DATABASE SariSariDB;
GO

USE SariSariDB;
GO

CREATE TABLE UserAccounts (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(255) UNIQUE NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    Surname NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    Address NVARCHAR(MAX) NOT NULL,
    Password NVARCHAR(255) NOT NULL
);

CREATE TABLE Categories (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Products (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Stock INT NOT NULL,
    CategoryId INT FOREIGN KEY REFERENCES Categories(Id),
    LowStockThreshold INT DEFAULT 20
);

CREATE TABLE Sales (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Date DATETIME DEFAULT GETDATE(),
    TotalAmount DECIMAL(12, 2) NOT NULL
);

CREATE TABLE SaleItems (
    Id INT PRIMARY KEY IDENTITY(1,1),
    SaleId INT FOREIGN KEY REFERENCES Sales(Id),
    ProductId INT FOREIGN KEY REFERENCES Products(Id),
    Quantity INT NOT NULL,
    PriceAtSale DECIMAL(10, 2) NOT NULL
);
