# Generated by Django 4.2.29 on 2026-03-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_saleitemmodel_cost_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitemmodel",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
